# HW2: Spelling Error Correction with Minimum Edit Distance and Confusion Matrix (V1)

#### Part 1: Implementing Minimum Edit Distance Algorithm

In this part, you will implement the Minimum Edit Distance (MED) algorithm, which calculates the minimum number of operations required to transform one word into another. The operations include insertion, deletion, and substitution of characters.

In [147]:

def min_edit_distance(word1, word2):
    m, n = len(word1), len(word2)
    dp = [[0] * (n + 1) for _ in range(m + 1)]

    # Initialize the matrix
    [dp[i].__setitem__(0, i) for i in range(m + 1)]
    [dp[0].__setitem__(j, j) for j in range(n + 1)]
    
    # Populate the matrix
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            # Cost of characters' match or substitution, adjusted by the confusion matrix
            cost = 0 if word1[i - 1] == word2[j - 1] else 1
            
            # Calculate minimum edit distance using dynamic programming
            dp[i][j] = min(
                dp[i - 1][j] + 1,    # Deletion
                dp[i][j - 1] + 1,    # Insertion
                dp[i - 1][j - 1] + cost  # Substitution
            )

    return dp[m][n]

In [149]:
def len_differ(word1, word2):
    if len(word1) > len(word2):
        return len(word1) - len(word2)
    else:
        return len(word2) - len(word1)

In [151]:
import pandas as pd

data = pd.read_csv("cognates_gold.csv")

In [153]:
# Creating lists to populate the columns of the data frame

eng_list = [] # english cognates
spa_list = [] # spanish cognates
med_list = [] # minimum edit distance between the pairs
ldif_list = [] # length differential between the pairs
melf_list = [] # minimum edit distance minus length differential
minlen_list = [] # length of the shorter word in the pair

for i in range (473):
    eng_str = ""
    for char in data.iloc[i][0]:
        if char.isalpha() == True:
            eng_str += char
    eng_list.append(eng_str)
    spa_str = ""
    for char in data.iloc[i][1]:
        if char.isalpha() == True:
            spa_str += char
    spa_list.append(spa_str)
    med = min_edit_distance(eng_str, spa_str)
    med_list.append(med)
    ldif = len_differ(eng_str, spa_str)
    ldif_list.append(ldif)
    melf = med - ldif
    melf_list.append(melf)
    minlen = min(len(eng_str), len(spa_str))
    minlen_list.append(minlen)

cols = {
    'English Cognate': eng_list, 
    'Spanish Cognate': spa_list, 
    'Min Edit Dist': med_list, 
    'Len Diff': ldif_list, 
    'MED - Ldif': melf_list, 
    'Min Len': minlen_list
        }
df = pd.DataFrame(cols)

df.head(25)

C:\Users\mande\AppData\Local\Temp\ipykernel_3112\2378400475.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for char in data.iloc[i][0]:
C:\Users\mande\AppData\Local\Temp\ipykernel_3112\2378400475.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for char in data.iloc[i][1]:

,English Cognate,Spanish Cognate,Min Edit Dist,Len Diff,MED - Ldif,Min Len
0,abandon,abandonar,2,2,0,7
1,abstract,abstracto,1,1,0,8
2,academy,academia,2,1,1,7
3,access,acceso,1,0,1,6
4,accommodate,acomodar,4,3,1,8
5,accompany,acompa√±ar,4,0,4,9
6,accumulate,acumular,3,2,1,8
7,acquire,adquirir,3,1,2,7
8,adapt,adaptar,2,2,0,5
9,adequate,adecuado,3,0,3,8
10,adjacent,adyacente,2,1,1,8
11,adjust,ajustar,3,1,2,6
12,administrate,administrar,2,1,1,11
13,adult,adulto,1,1,0,5
14,advocate,abogar,5,2,3,6
15,affect,afectar,3,1,2,6
16,aggregate,agregado,3,1,2,8
17,aid,ayuda,3,2,1,3
18,alter,alterar,2,2,0,5
19,alternative,alternativo,1,0,1,11
20,ambiguous,ambiguo,2,2,0,7
21,amend,enmendar,4,3,1,5
22,analogy,analog√≠a,2,1,1,7
23,analyze,analizar,3,1,2,7
24,annual,anual,1,1,0,5

In [155]:
df.describe()

       Min Edit Dist    Len Diff  MED - Ldif     Min Len
count     473.000000  473.000000  473.000000  473.000000
mean        2.291755    1.021142    1.270613    7.112051
std         1.337004    0.904073    1.100233    1.752154
min         0.000000    0.000000    0.000000    3.000000
25%         1.000000    0.000000    0.000000    6.000000
50%         2.000000    1.000000    1.000000    7.000000
75%         3.000000    1.000000    2.000000    8.000000
max         7.000000    5.000000    6.000000   14.000000

In [157]:
df.tail(50)

,English Cognate,Spanish Cognate,Min Edit Dist,Len Diff,MED - Ldif,Min Len
423,structure,estructura,2,1,1,9
424,style,estilo,3,1,2,5
425,submit,someter,5,1,4,6
426,subordinate,subordinar,2,1,1,10
427,subsequent,subsecuente,2,1,1,10
428,subsidy,subsidio,2,1,1,7
429,substitute,sustituir,3,1,2,9
430,successor,sucesor,2,2,0,7
431,sufficient,suficiente,2,0,2,10
432,sum,sumar,2,2,0,3
433,supplement,suplemento,2,0,2,10
434,survive,sobrevivir,5,3,2,7
435,suspend,suspender,2,2,0,7
436,sustain,sostener,5,1,4,7
437,symbol,s√≠mbolo,2,1,1,6
438,technical,t√©cnico,4,2,2,7
439,technique,t√©cnica,5,2,3,7
440,technology,tecnolog√≠a,3,0,3,10
441,temporary,temporario,2,1,1,9
442,tense,tenso,1,0,1,5
443,terminate,terminar,2,1,1,8
444,text,texto,1,1,0,4
445,theme,tema,2,1,1,4
446,theory,teor√≠a,3,0,3,6
447,thesis,tesis,1,1,0,5
448,trace,trazar,3,1,2,5
449,tradition,tradici√≥n,2,0,2,9
450,transfer,transferir,2,2,0,8
451,transform,transformar,2,2,0,9
452,transit,transitar,2,2,0,7
453,transmit,transmitir,2,2,0,8
454,transport,transportar,2,2,0,9
455,trend,tender,3,1,2,5
456,ultimate,√∫ltimo,4,2,2,6
457,uniform,uniforme,1,1,0,7
458,unify,unificar,4,3,1,5
459,unique,√∫nico,4,1,3,5
460,utilize,utilizar,2,1,1,7
461,valid,v√°lido,2,1,1,5
462,vary,variar,3,2,1,4
463,vehicle,veh√≠culo,3,1,2,7
464,version,versi√≥n,1,0,1,7
465,via,v√≠a,1,0,1,3
466,violate,violar,2,1,1,6
467,virtual,virtual,0,0,0,7
468,visible,visible,0,0,0,7
469,vision,visi√≥n,1,0,1,6
470,visual,visual,0,0,0,6
471,volume,volumen,1,1,0,6
472,voluntary,voluntario,2,1,1,9

In [159]:
df.to_csv("cognate_analysis.csv")

In [163]:
df_clean = df.drop(columns = ['Min Edit Dist', 'Len Diff', 'MED - Ldif', 'Min Len'])
df_clean.to_csv("cognate_gold_clean.csv")